- name: Update lvm configuration
  block:
  - name: Stringify snapshot_autoextend_percent setting
    ansible.builtin.set_fact:
      snapshot_create_snapshot_autoextend_percent_config: "activation/snapshot_autoextend_percent={{ snapshot_create_snapshot_autoextend_percent }}"
    when: snapshot_create_snapshot_autoextend_percent is defined
  - name: Stringify snapshot_autoextend_threshold setting
    ansible.builtin.set_fact:
      snapshot_create_snapshot_autoextend_threshold_config: "activation/snapshot_autoextend_threshold={{ snapshot_create_snapshot_autoextend_threshold }}"
    when: snapshot_create_snapshot_autoextend_threshold is defined
  - name: Stringify the new config
    ansible.builtin.set_fact:
      snapshot_create_new_lvm_config: >
        {{ snapshot_create_snapshot_autoextend_percent_config | default('') }}
         {{ snapshot_create_snapshot_autoextend_threshold_config | default('') }}
  - name: Set LVM configuration
    ansible.builtin.command: 'lvmconfig --mergedconfig --config "{{ snapshot_create_new_lvm_config }}" --file /etc/lvm/lvm.conf'
    changed_when: true
    when: ((snapshot_create_new_lvm_config | trim) | length) > 0

- name: Check for grubenv saved_entry
  ansible.builtin.lineinfile:
    name: /boot/grub2/grubenv
    regexp: ^saved_entry=
    state: absent
  check_mode: true
  changed_when: false
  failed_when: false
  register: snapshot_create_grubenv

- name: Add grubenv saved_entry
  ansible.builtin.shell: 'grubby --set-default-index=$(grubby --default-index)'
  changed_when: true
  when: snapshot_create_grubenv.found is defined and snapshot_create_grubenv.found == 0

- name: Create thick snapshots
  ansible.builtin.command:
    argv:
    - lvcreate
    - --snapshot
    - --name
    - "{{ item.lv }}_{{ snapshot_create_set_name }}"
    - --size
    - "{{ item.size }}"
    - "/dev/{{ item.vg }}/{{ item.lv }}"
  loop: "{{ snapshot_create_volumes }}"
  when: item.size != '0.0B'
  changed_when: true

- name: Create thin snapshots
  ansible.builtin.command:
    argv:
    - lvcreate
    - --snapshot
    - --name
    - "{{ item.lv }}_{{ snapshot_create_set_name }}"
    - "/dev/{{ item.vg }}/{{ item.lv }}"
  loop: "{{ snapshot_create_volumes }}"
  when: item.size == '0.0B'
  changed_when: true

- name: Required packages are present
  ansible.builtin.package:
    name:
    - gzip
    - tar
    state: present

- name: Create boot backup
  ansible.builtin.shell:
    cmd: |
      files=()
      for f in \
        initramfs-{{ ansible_kernel }}.img \
        vmlinuz-{{ ansible_kernel }} \
        System.map-{{ ansible_kernel }} \
        symvers-{{ ansible_kernel }}.gz \
        config-{{ ansible_kernel }} \
        .vmlinuz-{{ ansible_kernel }}.hmac \
        grub/grub.conf \
        grub2/grub.cfg \
        grub2/grubenv \
        loader/entries \
        efi/EFI/redhat/grub.cfg; do
        [ -e "/boot/$f" ] && files+=("$f")
      done
      tar --create --gzip --file /root/boot-backup-{{ snapshot_create_set_name }}.tgz -C /boot "${files[@]}"
    executable: /bin/bash
  changed_when: true
  when: snapshot_create_boot_backup

- name: Set boot backup permissions
  ansible.builtin.file:
    path: "/root/boot-backup-{{ snapshot_create_set_name }}.tgz"
    mode: '0644'
  when: snapshot_create_boot_backup
